# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none
#relative_permalinks: true
future: true
exclude: ["workspace"]

# Setup
title:               'bill noble'
tagline:             'meaning in flux'
description:         'My research website and (infrequent) blog about dialogue and semantic change. On Twitter <a href="https://twitter.com/winobes" target="_blank">@winobes</a>.'
url:                 winobes.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              bill noble
  url:               https://twitter.com/winobes
  email:             winobes@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
